### ISSUE TITLE
Office2016 SKUless

### ISSUE THREAD

**Issue by WardsParadox** [arubdesu/office-recipes#5]
While this downloads the latest version (as of now 16.22.*) it still uses the 16.17 version number which causes munki to not push the update.

**Comment by WardsParadox** [comment]
Changing FEED_URL to https://macadmins.software/latest.xml fixes it, but since it downloads the 2019 installers as well, I'm not sure if changing the recipe name would be a better idea with the change.

**Comment by arubdesu** [comment]
Hey Zack, I think people migrated to @rtrouton's version of [SKULess](https://github.com/rtrouton/autopkg_recipes/tree/master/MicrosoftOfficeSuite365), would you like to do me a solid and PR up a recipe-name-changed implementation? (He obvs doesn't include `.munki` variants.) I can dump the old ones afterwards since people can just roll back git if they miss 'em

**Comment by WardsParadox** [comment]
👍 Can do!
